CREATE TABLE buckets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE objects (
    id UUID PRIMARY KEY,
    bucket_name VARCHAR(255) NOT NULL REFERENCES buckets(name) ON DELETE CASCADE,
    key VARCHAR(1024) NOT NULL,
    physical_id UUID NOT NULL,
    size_bytes BIGINT NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT unique_bucket_key UNIQUE (bucket_name, key)
);
